### ISSUE TITLE
Job page

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#1]

**Comment by mir4a** [comment]
Link to check
http://jetthoughts.github.io/career.html

**Comment by pftg** [comment]
Досихпор прыгает когда скроллишь "High-Grade Working Solutions"

**Comment by pftg** [comment]
Досихпор прыгает когда скроллишь "High-Grade Working Solutions"

**Comment by pftg** [comment]
Цвета шрифтов и размеры не соответсвует дизайну

Как на дизайне http://note.io/13UQXTP
как у нас http://note.io/19NI1R4
