### ISSUE TITLE
Blog article issues with empty category and tags

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#100]
Please hide words like `in` and `tags` If there are no category and tags setup.

https://www.evernote.com/shard/s12/sh/ef88585a-2772-4603-9ce6-52bc4e1d772f/d60ea2d64f2b647ee5a32b1f42f502e5

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by pftg** [comment]
@mir4a have you deployed?

**Comment by mir4a** [comment]
http://jetthoughts-github-io-94-portf.herokuapp.com/

**Comment by mir4a** [comment]
@pftg but you can't test it for now - there is no post without categories

**Comment by pftg** [comment]
@tehhi42 please check this issue

**Comment by miry** [comment]
@tehhi42 pls check this issue. and comment here the status

**Comment by tehhi42** [comment]
Verified.
http://screencast.com/t/O16PF8KYUqXG

Resolved in #108
