### ISSUE TITLE
Create pngs with original colors

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#109]

**Comment by mir4a** [comment]
@tehhi42 @pftg you can download png from [here](https://drive.google.com/folderview?id=0B_pODa0XRi_yRUhBMF9jVjhLQXM&usp=sharing). Take a note there is two version of png: one with original design, and second with replaced all fonts with _Lato_ font-family (they're have `_lato.png` affix).

**Comment by tehhi42** [comment]
Verified.
