### ISSUE TITLE
Import blog articles

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#11]
https://github.com/jetthoughts/blog/tree/master/articles
- [x] code cleanup, remove indents
- [x] add default catagory

**Comment by annkuptsova** [comment]
@mir4a i`m sorry i am assigned to this issue but how can i test this?

**Comment by tehhi42** [comment]
@annkuptsova http://jetthoughts.github.io/blog/

**Comment by annkuptsova** [comment]
verified
