### ISSUE TITLE
Find a solution for hosting of blog pictures

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#114]

**Comment by tehhi42** [comment]
Now I host pictures from Flikr. Is there a better way of doing that?

**Comment by mir4a** [comment]
@tehhi42 I found interesting workaround about hosting images. Here http://stackoverflow.com/a/20958924/1540609 is proposed to upload images inside issues and then copy image url and paste it inside posts. The only benefit is that images are hosted inside github and attached into issues so everyone in our repository can manage them.

**Comment by tehhi42** [comment]
@mir4a Let's try this. How do I upload a picture inside an issue?

**Comment by mir4a** [comment]
@tehhi42 the same way how you did it on #122 and then you should just copy url of uploaded picture like this: 
![screen shot 2014-10-30 at 13 12 48](https://cloud.githubusercontent.com/assets/618900/4842458/c0ce9b96-6025-11e4-90f8-f0233975aee5.png)

or copy url which is appear in textarea after uploading has finished like this:
![screen shot 2014-10-30 at 13 13 50](https://cloud.githubusercontent.com/assets/618900/4842480/f470d978-6025-11e4-9511-88753d631132.png)

**Comment by tehhi42** [comment]
@mir4a Thank you.
