### ISSUE TITLE
Improve website loading speed

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#121]
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.jetthoughts.com%2F&tab=desktop

**Comment by tehhi42** [comment]
@miry @mir4a @pftg What recommendations do you consider necessary for website loading speed?

**Comment by mir4a** [comment]
@tehhi42 feels a bit faster. Found one annoying visual bug after optimization: when page is loaded I see background splashing and change to other. Suggest to add some kind of loader to hide this transformation before page has being loaded. What do you think?

**Comment by tehhi42** [comment]
@mir4a good job, it is faster now. 

@miry @pftg what do you think about the loader for background transformation?

**Comment by miry** [comment]
Now we see the font changes :)

**Comment by miry** [comment]
Also I think you can use async attribute. It seems we have some not async respurce.

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.jetthoughts.com%2F&tab=mobile

**Comment by mir4a** [comment]
@miry `async` attribute is using for script tag only. Loading of non-critical css can be done by javascript function. I think the issue with css can be done in this way:
1. Split styles on basic layout with most common style and other styles.
2. Load layout styles first inside head tag.
3. Load other styles via javascript, use loader for hiding styles transformations.

**Comment by tehhi42** [comment]
@mir4a @miry @pftg is this issue valid?
