### ISSUE TITLE
Fix website description

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#123]
http://screencast.com/t/Ii5ElJsMS4o

Let's change description to:

Ruby on Rails full stack web and mobile development team. We create Rails apps from scratch, offer support, optimisation and code review, provide RoR consulting services for startups and entrepreneurs. Use AngularJS and Backbone. Follow Agile workflow.

**Comment by mir4a** [comment]
@tehhi42 I've added this description, but for blog posts it would be replaced by blog post content truncated by 22 words. Suggest it would be great for SEO.

**Comment by tehhi42** [comment]
@mir4a will that be 22 first words?

**Comment by mir4a** [comment]
@tehhi42 yes it is. Also it adds "…" like this:
"Sometimes you don't want to write big javascript application just to have working remote modals in your rails application. The whole JSON-response..."

The best length of description is about 140-150 characters.

**Comment by tehhi42** [comment]
@mir4a thanks.
