### ISSUE TITLE
Optimize CSS Delivery for Mobile

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#137]
for http://www.jetthoughts.com/css/app.css we should do this https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery :
- extract critical css part in separate file
- inline this file in head section
- deffer loading of other's non critical css

**Comment by NazarKY** [comment]
use (if needed) [loadCSS](https://github.com/filamentgroup/loadCSS/)

**Comment by NazarKY** [comment]
We can do critical path but we have an issue with it - we can do it only for already builded files - so it mean that we will be need to push them with force.
