### ISSUE TITLE
WebFonts

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#138]
http://i.imgur.com/S2fGaYF.jpg

**Comment by pftg** [comment]
@mir4a can we optimize webfonts usage?

**Comment by mir4a** [comment]
@pftg sure but in this case we wouldn't be able to control FOUT effect – it's when text is invisible before custom font is loaded.

**Comment by pftg** [comment]
@mir4a как ты хочешь оптимизировать?

**Comment by tehhi42** [comment]
@mir4a any fresh ideas about how to fix this issue?

**Comment by mir4a** [comment]
@pftg @tehhi42 I don't think this is a big issue at all.

**Comment by tehhi42** [comment]
@mir4a @pftg so this issue may be closed?

**Comment by tehhi42** [comment]
@pftg please close if the issue is irrelevant.
