### ISSUE TITLE
MVP Landing Page

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#146]
![landing](https://cloud.githubusercontent.com/assets/5908100/5107937/9efef29c-700e-11e4-9299-45ec22960044.jpg)

![2014-11-19_1700](https://cloud.githubusercontent.com/assets/5908100/5107905/5505ece0-700e-11e4-8daa-b6166414fbd2.png)

**Comment by tehhi42** [comment]
Content https://docs.google.com/a/jetthoughts.com/document/d/1XaYaxY2cGK7uKPxjtPpuyANchtVqW0WVieT9MV-LnB4/edit

**Comment by mir4a** [comment]
Эпл я думаю не обидится
![landing_2](https://cloud.githubusercontent.com/assets/618900/5112668/f60e6d38-7031-11e4-8efd-0ae7c70152b0.jpg)

**Comment by mir4a** [comment]
http://jetthoughts-github-io-146-land.herokuapp.com/mvp.html

**Comment by tehhi42** [comment]
@pftg Please have a look http://jetthoughts-github-io-146-land.herokuapp.com/mvp.html

**Comment by tehhi42** [comment]
- [x] make the page responsive
- [x] optimize the page for mobile browsers
- [x] add the logo and the link to home website
  @mir4a any suggestions on where we can put it?
- [ ] add the links to the social networks
  ![2014-11-24_1745](https://cloud.githubusercontent.com/assets/5908100/5167612/1e163d78-7402-11e4-8c71-0a355ba2f766.png)
  https://github.com/jetthoughts/
  https://twitter.com/jetthoughts
  https://www.linkedin.com/company/352850?trk=tyah&trkInfo=tarId%3A1416844301285%2Ctas%3Ajetthought%2Cidx%3A1-1-1
  https://www.facebook.com/jetthoughts

**Comment by mir4a** [comment]
@tehhi42 check http://jetthoughts-github-io-146-land.herokuapp.com/mvp.html

**Comment by tehhi42** [comment]
@pftg LGTM, please review  http://jetthoughts-github-io-146-land.herokuapp.com/mvp.html

**Comment by pftg** [comment]
:+1:

**Comment by tehhi42** [comment]
@mir4a ready for production

**Comment by mir4a** [comment]
@tehhi42 take a look – I've added social links 
http://jetthoughts-github-io-146-land.herokuapp.com/mvp.html

**Comment by tehhi42** [comment]
@mir4a verified. Are we done here? Can it be deployed?

**Comment by mir4a** [comment]
@tehhi42 yes

**Comment by pftg** [comment]
@tehhi42 what with this issue?

**Comment by tehhi42** [comment]
@pftg this is done and verified, we did not publish and promote it because we decided with Anna that we do not have available people who have time for MVP development.

**Comment by annafoksha** [comment]
@tehhi42 @pftg Do you think we need to deploy it now?
