### ISSUE TITLE
Need JetThoughts logo (size 1400 * 425, under 4 mb)

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#150]

**Comment by mir4a** [comment]
![logo_1400](https://cloud.githubusercontent.com/assets/618900/5184388/ad93234a-74bf-11e4-83c6-5f52ed4e5f1a.png)
![logo_1400_transparent](https://cloud.githubusercontent.com/assets/618900/5184386/ad8c2a86-74bf-11e4-9226-98ba102613f0.png)
![logo_1400](https://cloud.githubusercontent.com/assets/618900/5184387/ad8f3618-74bf-11e4-98bd-9d91f124c55c.jpg)

**Comment by mir4a** [comment]
@tehhi42 logo in the middle without bg, it has transparent bg in case if you need it. Top logo in png format and smaller than bottom logo which is in jpg.

**Comment by pftg** [comment]
:+1:

**Comment by pftg** [comment]
do we have folder on google drive with all our logos?

**Comment by tehhi42** [comment]
Created Google Drive Folder https://drive.google.com/a/jetthoughts.com/folderview?id=0Bx5oX13Rd8Uobm1EN3h4LVJKM00&usp=sharing
