### ISSUE TITLE
Find a way to format code in blog posts without scroller

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#151]
http://www.jetthoughts.com/blog/tricks/2014/11/24/run-tests-against-multiple-ruby-versions-on-circleci.html

**Comment by tehhi42** [comment]
@mir4a please have a look when you have time.

**Comment by freevova** [comment]
@EnragedWildkin Bugs with borders of ruby code tables solved with installation sass v.2.3. This bugs solved in 212 issue. Please close this issue.

**Comment by tehhi42** [comment]
@EnragedWildkin please confirm that this issue is done and close.

**Comment by EnragedWildkin** [comment]
@tehhi42 Branch with fixes is not merged yet. Should be fixed in #212

**Comment by tehhi42** [comment]
@EnragedWildkin #212 is closed. Please confirm that this issue is fixed.

**Comment by EnragedWildkin** [comment]
@tehhi42 Fixed, but there is an issue with line numbers. See https://github.com/jetthoughts/jetthoughts.github.io/issues/221
