### ISSUE TITLE
Remove /about URL from .xml

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#156]
1
Warnings

URLs unreachable

When we tested a sample of the URLs from your Sitemap, we found that some of the URLs were unreachable. Please check your webserver for possible misconfiguration, as these errors may be caused by a server error (such as a 5xx error) or a network error between Googlebot and your server. All reachable URLs will still be submitted.
1
## URL: /about

Nov 21, 2013

**Comment by mir4a** [comment]
@tehhi42 don't mind this, because this is outdated warning (nov 21, 2013). We now don't have about url in our sitemap.
