### ISSUE TITLE
Fix 404 on Career and Portfolio pages

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#198]
http://www.jetthoughts.com/career/
http://www.jetthoughts.com/portfolio/

**Comment by mir4a** [comment]
@tehhi42  Github pages migrated to 3.0.3 version of jekyll (https://pages.github.com/versions/) and this caused in broken links, pagination and code highlighting. I tried to debug the issue and have not found yet nothing. But then I tried to setup blank new project with few posts and pagination enabled and it work. So, I suppose that problem may be in code highlighter or bad data or liquify hooks we're using in views.

I think I need someone to look on this.

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified 404 fix.
<img width="1271" alt="2016-02-10_1830" src="https://cloud.githubusercontent.com/assets/5908100/12953756/6c10251e-d024-11e5-8690-a105a2bf5b65.png">
<img width="1263" alt="2016-02-10_1830_1" src="https://cloud.githubusercontent.com/assets/5908100/12953757/6c14b6c4-d024-11e5-82a3-9248b9f89f0b.png">
Verified highlighting fix. 
<img width="1276" alt="2016-02-10_1831" src="https://cloud.githubusercontent.com/assets/5908100/12953838/cc676008-d024-11e5-87ed-292bffbb9987.png">
Verified a pagination fix.

**Comment by tehhi42** [comment]
@mir4a please create an issue for fixing code highlighting without a border.
