### ISSUE TITLE
Fix career page: markdown has not been rendered

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#204]
https://www.evernote.com/l/AAikoY-KCtxDMaH4MmRS9EFl_dgbmpPMzsQ

**Comment by mir4a** [comment]
@pftg done
We should use proper markdown markup (ref https://guides.github.com/features/mastering-markdown/)
Headings should have space symbol after dash `#` symbol and before heading text

**Comment by pftg** [comment]
@mir4a I thought that you added changes :(

**Comment by mir4a** [comment]
@pftg what kind of changes?

**Comment by mir4a** [comment]
check http://www.jetthoughts.com/career.html

**Comment by pftg** [comment]
:+1:
