### ISSUE TITLE
Home Page Content Fixes

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#23]
- [x] delete text
  http://screencast.com/t/CRJYRxLJ9U
- [x] update slider and icons on the slider
  http://screencast.com/t/pV1Vx6Rym
  The content is here (Why choose us) https://docs.google.com/document/d/12mpIT1fViFP8SGol2Ypayx5yWo3wwYEdXn5HXJszVLo/edit
- [x] add other social profiles to "Get social"
  http://screencast.com/t/XrrfyAvpOUw
- [x] change "something more" to "site map" and put a list of actual pages.
  http://screencast.com/t/zPuqmQdlMEb
- [x] improve text layout in What we offer field
  http://screencast.com/t/Syu47mRQ
- [x] 
  http://screencast.com/t/rNt7nLKP
- [x] 
  http://screencast.com/t/at9fkPhJRe71
  http://screencast.com/t/nWbPc9MA
  http://screencast.com/t/pQauMt5p9r4P
- [ ] laptop is not displayed on iPad
  http://imm.io/1lWT3

**Comment by mir4a** [comment]
@tehhi42 you can check here (except last two subtasks) http://jetthoughts.github.io

**Comment by miry** [comment]
@mir4a перед работой нужно обсудить эти фиксы
- [ ]  http://note.io/1fd341U
- [ ] На ноуте первые два тексты серые, последний же синий. Мне проще читалось на послденем. На первых двух Белый на сером плохо выделялось. Сравните плиз с дизайном.
- [ ] http://note.io/1fd406b
- [x] http://note.io/1fd4hWR

**Comment by mir4a** [comment]
@tehhi42 take a look. Note, as we wanted to change slider to smth else, some of the tasks are not actual

**Comment by tehhi42** [comment]
Current fixes are verified.
