### ISSUE TITLE
Updated content to be framework agnostics

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#246]
Need to extract all metadata, titles and descriptions from view-source:https://thoughtbot.com/ and put it here:

* ![](https://cl.ly/0a2H2m0N3k28/Image%202018-04-15%20at%2018.44.51.public.png)
* ![](https://cl.ly/3C3Q2h08191N/Image%202018-04-15%20at%2018.45.53.public.png)

**Comment by sweatC** [comment]
@pftg I'm just wondering what "framework agnostics" means? I didn't find any sensible explanation. Could you bring more details about content updating.
Thank you!

**Comment by pftg** [comment]
@sweatC I'll update it later. content related stuff I'll do myself
