### ISSUE TITLE
Verify on Mobile and Desktop Browsers

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#248]

**Comment by sweatC** [comment]
First loading looks weird
Phone number
![image](https://user-images.githubusercontent.com/15202961/38436688-fb1f30a4-39dd-11e8-9321-4c707d88ac37.png)
Mobile version
![screenshot_2018-04-06-21-14-18](https://user-images.githubusercontent.com/15202961/38437349-d3c4c828-39df-11e8-8ec2-b749ccd26a8e.png)
