### ISSUE TITLE
Comparison of the design

### ISSUE THREAD

**Issue by annafoksha** [jetthoughts/jt.github.io#25]
Задумка была: поставить рядом оригинальный дизайн, открыть наш сайт и сравнить вид.
Сначала хотела подробно перечислить различия, потом подумала показать стрелочками, но все это слишком долго, решила что проще поставить циферки. Хотя не всегда понятно на что именно они показывают...
anyway, скринов я наделала:
http://dl.dropbox.com/u/110035603/Selection_001.png
http://dl.dropbox.com/u/110035603/Selection_002.png
http://dl.dropbox.com/u/110035603/Selection_003.png
http://dl.dropbox.com/u/110035603/Selection_004.png
http://dl.dropbox.com/u/110035603/Selection_005.png
http://dl.dropbox.com/u/110035603/Selection_006.png
http://dl.dropbox.com/u/110035603/Selection_007.png
http://dl.dropbox.com/u/110035603/Selection_008.png
http://dl.dropbox.com/u/110035603/Selection_009.png
http://dl.dropbox.com/u/110035603/Selection_011.png
http://dl.dropbox.com/u/110035603/Selection_012.png
http://dl.dropbox.com/u/110035603/Selection_013.png
http://dl.dropbox.com/u/110035603/Selection_014.png
Предлагаю для начала исправить то что понятно и что исправить возможно. Тогда будем еще раз смотреть.

**Comment by mir4a** [comment]
@annkuptsova pls verify only home page

**Comment by annkuptsova** [comment]
http://dl.dropbox.com/u/19920739/JetThoughts%20Home%20-%20Google%20Chrome_048.png

**Comment by annkuptsova** [comment]
http://dl.dropbox.com/u/19920739/Workspace%201_049.png

the rest pages will be checked later

**Comment by tehhi42** [comment]
@annkuptsova check only home page please

**Comment by mir4a** [comment]
@annkuptsova you can check homepage now

**Comment by annkuptsova** [comment]
http://dl.dropbox.com/u/19920739/JetThoughts%20Home%20-%20Google%20Chrome.png

http://dl.dropbox.com/u/19920739/JetThoughts%20Home%20-%20Google%20Chrome%28001%29.png

**Comment by annkuptsova** [comment]
http://dl.dropbox.com/u/19920739/Workspace%201%28001%29.png extra space

**Comment by tehhi42** [comment]
@mir4a is this issue solved?

**Comment by miry** [comment]
@annkuptsova pls verify again, and do not use ZOOM

**Comment by annkuptsova** [comment]
why is this line bold and italic unlike design ?  http://dl.dropbox.com/u/19920739/Agile%20Web%20%26%20Mobile%20Development%20%7C%20JetThoughts%20-%20Google%20Chrome.png 

it seems to me that this proportion is incorrect http://dl.dropbox.com/u/19920739/Workspace%201%28003%29.png

**Comment by annkuptsova** [comment]
we need to cut this paragraph so columns look similar http://dl.dropbox.com/u/19920739/Agile%20Web%20%26%20Mobile%20Development%20%7C%20JetThoughts%20-%20Google%20Chrome%28001%29.png

**Comment by tehhi42** [comment]
> we need to cut this paragraph so columns look similar >http://dl.dropbox.com/u/19920739/Agile%20Web%20%26%20Mobile%20Development%20%7C%20JetThoughts%20-%20Google%20Chrome%28001%29.png 

Let's cut out this paragraph

**Comment by miry** [comment]
@mir4a can you look to

> it seems to me that this proportion is incorrect
> http://dl.dropbox.com/u/19920739/Workspace%201%28003%29.png
1. Font is much differ from designed
2. Proportion incorrect too. I like bigger font size and bold text like in design.

Also pls update what the issue with fonts here.

**Comment by miry** [comment]
@mir4a pls update the status

**Comment by mir4a** [comment]
@miry or @tehhi42 or @annkuptsova  pls verify.

**Comment by tehhi42** [comment]
@mir4a Miry's comment is still relevant. Fonts differ from the initial design.

**Comment by mir4a** [comment]
@tehhi42 no it's not! Because this font is from first iteration of design, after that we decided to change custom font. But the designer didn't change mockups and only provided names of the fonts. That is why they're differ.

**Comment by tehhi42** [comment]
@mir4a I have compared the latest version of design with the second version of fonts.
http://minus.com/lblA5X6VS6aJbA
http://minus.com/lGDX3OR5Hawa3
http://minus.com/lWtmTzeGN7vq4
http://minus.com/lmNVY55mXrRq0
http://minus.com/l1ND5ekI2PUYn
http://minus.com/lq5XUZjDYt6VP

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
@mir4a http://minus.com/l8HeaBBvCzAw2
http://minus.com/lbj6JmraJeqldM

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified.
