### ISSUE TITLE
Do not load video for mobile devices

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#250]

**Comment by andriyParashchuk** [comment]
Done

**Comment by pftg** [comment]
@andriyParashchuk how to verify?

**Comment by andriyParashchuk** [comment]
@pftg Video has property display: none in mobile. So it not load for mobile
You can verify at open site on mobile device

**Comment by pftg** [comment]
could you confirm that it has been deployed and provide screenshots, also ask to verify and close

**Comment by andriyParashchuk** [comment]
Yes, sure
![1523958298284](https://user-images.githubusercontent.com/23320186/38862323-40b03a3e-423d-11e8-8e92-14fbfcca427f.jpg)
