### ISSUE TITLE
Setup Deployment on GitHub pages

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#254]
Need to setup github pages deployemnt.

For now we have error on push. So we need to fix plugins for Jekyll or setup static page compilation and deployment.

You could test by use `gh-page` on jetthoughts/lyoutube https://cl.ly/2Z1w0w213h3a/Image%202018-03-27%20at%2011.40.24.public.png repository in order to test github page deployment

**Comment by andriyParashchuk** [comment]
Added static code in master branch
site deployed on https://www.jetthoughts.com
