### ISSUE TITLE
Found issues

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#262]
Text the same :point_down: 
![image](https://user-images.githubusercontent.com/15202961/38748179-fd68753c-3f55-11e8-8da6-42371fb2039b.png)

---

carousel doesn't work properly.
Come on, he switches from AI to Farius then again on AI and breaks.
https://www.useloom.com/share/0b9be2ca95934218b3e7c20f214b61eb

---

Need to add styles for scroll and fix bug with text typing.
![image](https://user-images.githubusercontent.com/15202961/38748881-542b5c02-3f58-11e8-8ee2-e9fd9fbc367f.png)
![image](https://user-images.githubusercontent.com/15202961/38748887-59679956-3f58-11e8-8a72-a9bd2036e190.png)

**Comment by pftg** [comment]
@sweatC please translate this into english

**Comment by pftg** [comment]
@sweatC please split this issue into several issues

**Comment by sweatC** [comment]
@pftg will do
Check this out to Verify: #276 #277 #278
