### ISSUE TITLE
[Performance] Eliminating Unnecessary Downloads

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#266]
- Inventory your own assets and third-party assets on your pages.
- Measure the performance of each asset: its value and its technical performance.
- Determine if the resources are providing sufficient value.
- Eliminate it if it needed.

**Comment by sweatC** [comment]
@pftg please approve if it has unnecessary downloads.
![image](https://user-images.githubusercontent.com/15202961/39421050-f87fe81c-4c6f-11e8-9b85-0cfb06940d9d.png)
![image](https://user-images.githubusercontent.com/15202961/39421104-34986432-4c70-11e8-9ecb-25c85816a91b.png)

**Comment by andriyParashchuk** [comment]
@sweatC where did you get content.css and livereload?

![1525157376479](https://user-images.githubusercontent.com/23320186/39464314-3946683e-4d25-11e8-873b-2633948bceb0.jpg)

**Comment by pftg** [comment]
@sweatC please use incognito mode in order to remove all chrome plugins

**Comment by pftg** [comment]
@sweatC could you find an answer on please approve if it has unnecessary downloads, yourselves

**Comment by sweatC** [comment]
@pftg @andriyParashchuk Site doesn't have redundant downloads.
![image](https://user-images.githubusercontent.com/15202961/39510244-bbefeb80-4df1-11e8-9a8b-b443639c4ecb.png)

**Comment by obliviusm** [comment]
@sweatC reviewer should close PR, not you
