### ISSUE TITLE
Automatize merging in master via CircleCI

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#267]
You just need to integrate Github with CircleCI. 
So that when you create PR and it was approved,
you can simply merge your code with the master branch. 

Additional info you can find here: 

- https://circleci.com/integrations/github/
- http://adaptivejs.mobify.com/v2.0/docs/1-add-a-project-to-circleci/
- https://github.com/marketplace/circleci
- https://www.youtube.com/watch?v=CB7vnoXI0pE&list=PLRqwX-V7Uu6bLqwFa52YGEHy-L1-D_Ve-

**Comment by andriyParashchuk** [comment]
Fixed in #263
