### ISSUE TITLE
Register twitter and facebook apps

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#27]

**Comment by miry** [comment]
@mir4a pls check this: https://dev.twitter.com/docs/tweet-button#properties

**Comment by miry** [comment]
I don't see the place where I can put Facebook or Twitter app ids. @mir4a pls post here the line code refer.

**Comment by mir4a** [comment]
@miry here is example of desirable result https://dev.twitter.com/docs/cards/types/summary-card

**Comment by mir4a** [comment]
and here is explanation for facebook http://stackoverflow.com/a/10836476/1540609
Facebook ids is not required, but I think twitter:cards we must have

**Comment by tehhi42** [comment]
@miry what is the status of this issue?

**Comment by miry** [comment]
@tehhi42 sent request to approve twitter cards. The Facebook app id is not required anymore.
