### ISSUE TITLE
[Performance] Critical Request Chains

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#274]
The Critical Request Chain is a concept from the Critical Rendering Path (CRP) optimization strategy. CRP enables the browser to load a page as quickly as possible by prioritizing which resources get loaded and the order in which they load.
![image](https://user-images.githubusercontent.com/15202961/39081906-702fe0bc-4552-11e8-84aa-637e6273140f.png)

**Comment by pftg** [comment]
@sweatC this just info issue - need to have some action and acceptance test. What are you going to implement in the issue?

**Comment by pftg** [comment]
![](https://cl.ly/2o3B0o2a1M05/Image%202018-04-29%20at%2013.21.50.public.png)

**Comment by sweatC** [comment]
It was done in first iteration. So not actual for now.
