### ISSUE TITLE
[Performance] JavaScript boot-up time is too high

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#275]
Check this out:
- [JavaScript Start-up Optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/)
- [Loading Third-Party JavaScript](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/)

![image](https://user-images.githubusercontent.com/15202961/39081944-2c8f5878-4553-11e8-9114-adc3689bb691.png)

**Comment by pftg** [comment]
https://github.com/h5bp/html5-boilerplate

**Comment by sweatC** [comment]
It was done in first iteration. So not actual for now.
