### ISSUE TITLE
icons for home page

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#28]
thenounproject.com as reference

**Comment by tehhi42** [comment]
cost advantage:
http://thenounproject.com/term/piggy-bank/30078/

client-oriented approach
http://thenounproject.com/term/vitruvian-man/2532/

Effective communication and reliable tech support
http://thenounproject.com/term/customer-service/15877

Efficiency and reliability
http://thenounproject.com/term/secure/19512/

High-Grade Working Solutions
brain icon is ok

**Comment by mir4a** [comment]
Иконка со свиньей почему-то не хотела скачиваться, заменил на другую

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified
