### ISSUE TITLE
Title for home page

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#29]
Find or use old title

**Comment by tehhi42** [comment]
Title: JetThoughts: Agile Software Development
Description: JetThoughts is a web application development company, providing website design and programming services on Ruby on Rails.

**Comment by miry** [comment]
@tehhi42 I think In title should be present at least word "JetThoughts"

**Comment by miry** [comment]
examples: http://www.tilde.io, http://37signals.com, http://www.thoughtworks.com

**Comment by tehhi42** [comment]
Yes, sure.

**Comment by tehhi42** [comment]
@miry @mir4a Did you decide to use the old description?

**Comment by miry** [comment]
@tehhi42 we still wait for your final title and description.

**Comment by tehhi42** [comment]
I have updated comment 11 days ago and included word "Jetthoughts" in the title. Please review it

Title: JetThoughts: Agile Software Development
Description: JetThoughts is a web application development company, providing website design and programming services on Ruby on Rails.

**Comment by miry** [comment]
@tehhi42 I suggest to not update old comments, because no one read old one.

I found: `Agile Web & Mobile Development | JetThoughts` as title what do you think?

**Comment by tehhi42** [comment]
@miry I think it is good. Let's stick to it.

**Comment by miry** [comment]
@annafoksha pls verify

**Comment by annafoksha** [comment]
This is a phrase from our old website. But nothing stops us from using it here of course.
I'd prefer to see how it looks on a new bg before verifying. 

On the other hand, when Lena specified me where it will be displayed, I verify this.
