### ISSUE TITLE
Prioritize visible content

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#294]
From https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.jetthoughts.com%2F&tab=desktop

![](https://cl.ly/2F1y0H083n2r/Image%202018-04-29%20at%2013.24.27.public.png)

Ref: https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent

**Comment by sweatC** [comment]
It was done in first iteration. So not actual for now.
