### ISSUE TITLE
Mobile Ready

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#298]
Support on Mobile Devices

- [x] Fast
- [x] No Bugs or UI problems

**Comment by obliviusm** [comment]
Done

Verified in: https://github.com/jetthoughts/jetthoughts.github.io/issues/300
Fixed in: https://github.com/jetthoughts/jetthoughts.github.io/pull/314 https://github.com/jetthoughts/jetthoughts.github.io/pull/312
