### ISSUE TITLE
Map on Home Page

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#30]
Делаем пока так, в процессе посмотрим, что получается
http://minus.com/lxc88bdrq2E1w
Подложка вот такого синего цвета
http://minus.com/lwehBiHjibGZo

**Comment by mir4a** [comment]
подложка не загрузилась

**Comment by tehhi42** [comment]
загрузила еще раз

**Comment by mir4a** [comment]
Опять 25, шрифты там старые

**Comment by mir4a** [comment]
Это старый макет, шрифт там будет такой же как и на странице, с максимальной похожестью на макет

**Comment by tehhi42** [comment]
используй те, которые решили использовать везде.

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Добавь, пожалуйста, выше карты примерно 1,5 больших квадрата фона, сейчас вверху мало места. А карту расположи по центру.

**Comment by pftg** [comment]
Цвет фона, еще надо подобрать, а то сливаеться.

**Comment by mir4a** [comment]
Попробовал вставить размытый фон острова Ко Лан, получилось свежо и приятно. Что скажете? http://jetthoughts.github.io/

**Comment by mir4a** [comment]
@miry @tehhi42 @pftg check pls

**Comment by miry** [comment]
@annkuptsova pls verify

**Comment by annkuptsova** [comment]
we need to discuss design of main page when Miroslav will be on Samui

**Comment by pftg** [comment]
@annkuptsova verify and discuss is not the same, just please paste your report, and then we will discuss it with Miroslav

**Comment by annkuptsova** [comment]
@pftg  i can not verify it, Lena asked to do add some extra space in previous background. Miroslav changed background and we deed not approved it, so i can not verify this task until it is back to previous version.

**Comment by mir4a** [comment]
Guys, take a look at this variants of homepage bgs
![screen shot 2014-02-25 at 18 32 45](https://f.cloud.github.com/assets/618900/2256996/e778a2be-9e10-11e3-8cda-5a2ec823aba1.png)
![screen shot 2014-02-25 at 18 30 57](https://f.cloud.github.com/assets/618900/2256997/e7a89ec4-9e10-11e3-8195-f827099caecf.png)
![screen shot 2014-02-25 at 18 19 23](https://f.cloud.github.com/assets/618900/2256998/e7d90fd2-9e10-11e3-9fb6-a549399d265d.png)
![screen shot 2014-02-25 at 18 19 08](https://f.cloud.github.com/assets/618900/2256999/e7da92ee-9e10-11e3-823d-abff003d0a18.png)

**Comment by annkuptsova** [comment]
i desperately like third variant

**Comment by tehhi42** [comment]
Yes, the third is the best. But why the beach at the background?

**Comment by annafoksha** [comment]
мне нравится голубой фон без всяких пятен

**Comment by tehhi42** [comment]
Подобрала варианты фона с самолетами. 
![400_f_50374568_l7v7qmvofkfvrjxgagcwveaaoqtrlvnx](https://f.cloud.github.com/assets/5908100/2281688/3867e928-9fa1-11e3-9fba-58b1a46ba7d1.jpg)
![0474](https://f.cloud.github.com/assets/5908100/2281690/386faf14-9fa1-11e3-82f1-3224090f2784.jpg)
![img_6479](https://f.cloud.github.com/assets/5908100/2281689/386f1608-9fa1-11e3-9918-e11c863af33c.JPG)
![new_sample_962](https://f.cloud.github.com/assets/5908100/2281691/38726cb8-9fa1-11e3-8048-a7dd5684883f.jpg)
![plane clouds](https://f.cloud.github.com/assets/5908100/2281692/387905fa-9fa1-11e3-8b5e-c7fb1753147c.jpg)
![new_sample_2001](https://f.cloud.github.com/assets/5908100/2281693/3879b19e-9fa1-11e3-8997-e1558eb632cc.jpg)
Можно попробовать поставить несколько и подумать, нравится ли нам идея с самолетом вообще. Не хочется, чтобы сайт был похож на сайт авиакомпании.

**Comment by mir4a** [comment]
Вот ещё варианты:
![screen shot 2014-03-03 at 5 57 11](https://f.cloud.github.com/assets/618900/2306544/18a54388-a28a-11e3-87b9-65266f231de1.png)
![screen shot 2014-03-03 at 6 00 17](https://f.cloud.github.com/assets/618900/2306546/18a659c6-a28a-11e3-8749-34f2b5d18606.png)
![screen shot 2014-03-03 at 6 02 30](https://f.cloud.github.com/assets/618900/2306547/18a65ab6-a28a-11e3-8e5c-5e6a305acaef.png)
![screen shot 2014-03-03 at 6 05 22](https://f.cloud.github.com/assets/618900/2306548/18a7bb04-a28a-11e3-9228-a9e34932e6db.png)
![screen shot 2014-03-03 at 5 58 08](https://f.cloud.github.com/assets/618900/2306545/18a56b92-a28a-11e3-8369-9f57a4242791.png)
![screen shot 2014-03-03 at 6 10 47](https://f.cloud.github.com/assets/618900/2306549/18a80c44-a28a-11e3-89b1-c9a7043e0567.png)

**Comment by pftg** [comment]
Вот то что мне больше всего приглянулось, а то кажеться что мы авиа компания ;)
![screen shot 2014-03-03 at 5 57 11](https://f.cloud.github.com/assets/618900/2306544/18a54388-a28a-11e3-87b9-65266f231de1.png)
![screen shot 2014-03-03 at 5 58 08](https://f.cloud.github.com/assets/618900/2306545/18a56b92-a28a-11e3-8369-9f57a4242791.png)

**Comment by tehhi42** [comment]
Я за 1й. Но карту можно убрать. Как думаете?

**Comment by annafoksha** [comment]
Both are good. Fonts are better on the first one.

**Comment by tehhi42** [comment]
@mir4a Let's stick to the first one. With the same fonts.
