### ISSUE TITLE
Verify on Mobile Devices

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#300]
iPhone 5s, 6
Android
tablets

verify load speed

use ghost inspector, browserling, 
http://www.responsinator.com/?url=http://jetthoughts.com
http://quirktools.com/screenfly/

Need check with designe for mobile - https://drive.google.com/drive/u/1/folders/1yVjuYSwctYQmBLw7YHrWmHIPHVq70ox7

**Comment by obliviusm** [comment]
Blocked by #288

**Comment by sweatC** [comment]
@pftg @obliviusm @andriyParashchuk please verify.
Checked styles and working status on Mobile devices.
https://www.useloom.com/share/1e3a071677a2476ea372f987cbe87745
Checked loading speed on mobile devices.
https://www.useloom.com/share/9431c517cd48430aba9395ee9da98700

**Comment by pftg** [comment]
@sweatC what bugs have you found?

**Comment by sweatC** [comment]
@pftg I haven't found anything strange.
I think mobile version is ready.

**Comment by obliviusm** [comment]
@sweatC sorry, but that version of site was outdated
now it is updated. please re-test it again

**Comment by sweatC** [comment]
@obliviusm will do.

**Comment by andriyParashchuk** [comment]
Updated description

**Comment by sweatC** [comment]
LGTM

**Comment by obliviusm** [comment]
@sweatC is it identical to mobile design?

**Comment by sweatC** [comment]
@obliviusm here what I found.
In Welcome section, we don't have background video and the arrow should be lower.
Design:
![kazam_screenshot_00003](https://user-images.githubusercontent.com/15202961/40012563-c2ef32d0-57b3-11e8-84db-432f0ee0226e.png)
Real app:
![screenshot_2018-05-14-20-13-48](https://user-images.githubusercontent.com/15202961/40012599-d20f4cfa-57b3-11e8-929f-47e3b9153f5d.png)
In Services section services label has different color. Last text line has only one word `productivity`.
Design:
![kazam_screenshot_00004](https://user-images.githubusercontent.com/15202961/40012770-5d00689e-57b4-11e8-96ca-5c587511641b.png)
Real app:
![screenshot_2018-05-14-20-19-55](https://user-images.githubusercontent.com/15202961/40012783-62a8cafc-57b4-11e8-9f0c-88d59679d933.png)
Footer section has different places for Email, Telephone and Description fields. Also, between `JetThoughts` label and copyright in the design we have much more spaces.
Design:
![kazam_screenshot_00005](https://user-images.githubusercontent.com/15202961/40013043-27ef65c8-57b5-11e8-9954-77154278ac28.png)
Real app:
![screenshot_2018-05-14-20-27-06](https://user-images.githubusercontent.com/15202961/40013058-31d151f0-57b5-11e8-87c1-b7ce82b124ed.png)
The others sections looks great.

**Comment by obliviusm** [comment]
@andriyParashchuk pls check and tell if we should fix these or was it done on purpose?

**Comment by andriyParashchuk** [comment]
@sweatC pls write size display device on testing
- arrow in main screen i think can be fix
- We hide video bg on mobile
- Blue arrow in services - is hovered
- Footer section has different places for Email, Telephone and Description fields. - Can be fix
- Also, between JetThoughts label and copyright in the design we have much more spaces - maked equally spaces like email and phone label above but can be fix

**Comment by sweatC** [comment]
@andriyParashchuk Samsung J2: 4,7'', 960x540

**Comment by andriyParashchuk** [comment]
Will be fixed in #312

**Comment by andriyParashchuk** [comment]
LGTM

**Comment by sweatC** [comment]
OK. We have decided to fix 2 things:
- arrow in main screen
- description field in footer
