### ISSUE TITLE
Ignore in Google Analytics all Developers and GhostInspector and other tools

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#301]

**Comment by sweatC** [comment]
@pftg  I want to use Custom Filter to exclude`app.ghostinspector.com` and IP address filter to exclude all developers. For this I need to have Edit permission in my account.
See: 
https://support.google.com/analytics/answer/1034842?hl=en&ref_topic=1034830
https://support.google.com/analytics/answer/1034823

**Comment by pftg** [comment]
@sweatC granted edit rights for you

**Comment by sweatC** [comment]
In this issue I've created two filters. One for excluding GhostInspector, Quirktools, Surge and the other one for excluding localhost. Also It will take time (as much as 24 hours) before filter effects become visible.
![image](https://user-images.githubusercontent.com/15202961/39876742-a41cf494-547c-11e8-8e3e-ebb730070bbf.png)

**Comment by obliviusm** [comment]
@sweatC call to action? who should review? how to check it? when to check it?

**Comment by sweatC** [comment]
@pftg @obliviusm @andriyParashchuk  please review. You need to log in from your [Google Analytics](https://analytics.google.com) account. Click Admin from the left sidebar and choose Filters tab from View column. Then check filters above.
For more details:
https://support.google.com/analytics/answer/1034842?hl=en&ref_topic=1034830
https://support.google.com/analytics/answer/1034840?hl=en&ref_topic=1034830
https://support.google.com/analytics/answer/6046990

**Comment by pftg** [comment]
@sweatC please add screenshots

**Comment by sweatC** [comment]
Admin panel and filters tab.
![image](https://user-images.githubusercontent.com/15202961/39909638-4b31fd90-54fc-11e8-95f4-377b47735936.png)
View column. Filters. Two filters.
![image](https://user-images.githubusercontent.com/15202961/39909668-6fb7703c-54fc-11e8-9230-fb74d3545e36.png)
First filter:
![image](https://user-images.githubusercontent.com/15202961/39909720-b8441710-54fc-11e8-98e1-70be9412b64b.png)
Second filter:
![image](https://user-images.githubusercontent.com/15202961/39909748-d4e29b6c-54fc-11e8-94ed-6956c5f28424.png)

**Comment by obliviusm** [comment]
@sweatC please check that ingored sites are actually not used in analytics
i think it is possible to do with realtime tool

**Comment by pftg** [comment]
you could run ghostinstpector tool several times and then re-check on ga

**Comment by pftg** [comment]
Need to reverify tomorrow after GA will apply filter rules

**Comment by pftg** [comment]
Looks like is woring. @andriyParashchuk please verify

**Comment by obliviusm** [comment]
@sweatC checked surge with my url `http://jt-pr288.surge.sh/?source=surge`. definitely not ignored:
![image](https://user-images.githubusercontent.com/1386397/39996643-e0ec9208-5788-11e8-96bc-3adc1271eda5.png)

**Comment by sweatC** [comment]
@obliviusm fixed. 
Check this out: https://www.useloom.com/share/f030e11fc6434c9790911a3997d68da1

**Comment by obliviusm** [comment]
@sweatC what about ghostinspector and localhost?

**Comment by sweatC** [comment]
@obliviusm Real time panel doesn't show activity on ghostinspector and localhost too.

**Comment by obliviusm** [comment]
@sweatC now i don't get any active users in realtime. even if i visit https://www.jetthoughts.com
does it work fine for you?

**Comment by sweatC** [comment]
@obliviusm pls check
Ignored localhost, responsinator, quirktools, surge, ghostinspector, debug, circleci, github.
Tested all this cases.

**Comment by pftg** [comment]
could we setup that if there is in url param like 'dev' then we should ignore in GA. what do you think. we do not need to filter any such tools

**Comment by obliviusm** [comment]
@pftg do you propose to always use param like 'dev'  when we use services like surge or ghostinspector?

**Comment by obliviusm** [comment]
@sweatC by the way i checked http://jt-pr288.surge.sh/ and it is showed in realtime

**Comment by obliviusm** [comment]
@pftg @sweatC can we use instead `include` filter and allow only `jetthoughts.com` ?

**Comment by sweatC** [comment]
@obliviusm created filter that includes traffic only from `jetthoughts.com` host name.

**Comment by obliviusm** [comment]
@sweatC does it help to ignore surge, ghost and localhost?
does it allow jetthoughts.com ?
can you test it?

**Comment by sweatC** [comment]
@obliviusm I didn't test it yet.

**Comment by sweatC** [comment]
@obliviusm tested
https://www.useloom.com/share/8d9cda1b5cd646f985bbe17b3f45f485

**Comment by obliviusm** [comment]
@sweatC looks good
but please change params filter to height and stop_animation. as in ghost
and remove filter for quirktools, responsinator. i checked and it actually doesn't ignore those sites.

then we are good

![page 3](https://user-images.githubusercontent.com/1386397/40118263-194b5964-5922-11e8-8d59-ca3d5f6a6b60.png)

**Comment by sweatC** [comment]
@obliviusm Done

**Comment by obliviusm** [comment]
LGTM
