### ISSUE TITLE
Check design

### ISSUE THREAD

**Issue by andriyParashchuk** [jetthoughts/jt.github.io#315]
Need to compare the designs .psd that are in  https://drive.google.com/drive/u/1/folders/1yVjuYSwctYQmBLw7YHrWmHIPHVq70ox7
invision in https://projects.invisionapp.com/share/EABU3IP46
and Figma in https://www.figma.com/file/wmRuaLaG0wwnOE9kBWfnMn/Jetthoughts-2?node-id=1%3A2

**Comment by sweatC** [comment]
Summary:
I had checked three links above, so what I found.
At Invision we have old design. One year old comments and many details were changed.
So here I would post Figma and Google drive differences.
When I checked Mobile versions I noticed one difference. It was in footer.
GD:
![image](https://user-images.githubusercontent.com/15202961/40194031-bddf70e2-5a11-11e8-9eca-a39dcfccafe4.png)
Figma:
![image](https://user-images.githubusercontent.com/15202961/40194050-cbd943b2-5a11-11e8-8117-561072dbe4bb.png)
Desktop versions looking the same.
@pftg @obliviusm @andriyParashchuk
