### ISSUE TITLE
Check and fix IU on 667x375

### ISSUE THREAD

**Issue by andriyParashchuk** [jetthoughts/jt.github.io#318]
https://app.ghostinspector.com/tests/5aec674088762859e5a61d1d

**Comment by andriyParashchuk** [comment]
this bug is only in the tests, because at the tests set the height of the section, but the screen itself is stretched, so the media requests for height are triggered

On device it is ok:

![1526902872767](https://user-images.githubusercontent.com/23320186/40306148-3295532e-5d06-11e8-8da4-c22147d9aef2.jpg)
![1526676257431](https://user-images.githubusercontent.com/23320186/40306130-1e91b05c-5d06-11e8-8002-d0c4af1df781.jpg)
![1526902830663](https://user-images.githubusercontent.com/23320186/40306107-0497e0e0-5d06-11e8-87e1-6314c829ebe8.jpg)
![1526902817112](https://user-images.githubusercontent.com/23320186/40306108-04c67d74-5d06-11e8-9d2e-45dd76524a6b.jpg)
![1526902803446](https://user-images.githubusercontent.com/23320186/40306109-04ece2ac-5d06-11e8-9343-b66637f04839.jpg)

**Comment by andriyParashchuk** [comment]
@pftg @obliviusm @sweatC pls check and close

**Comment by pftg** [comment]
@andriyParashchuk we need to fix tests in order to be more real.

**Comment by pftg** [comment]
just place it on ready list, and do not fix it for now

**Comment by pftg** [comment]
@andriyParashchuk any updates on this?

**Comment by andriyParashchuk** [comment]
I have not yet found a solution for this task
There is a problem in that we check height viewport on inverted mobile screen. Because ghostinspector stretches screen on max height, we have error
This problem get only then testing inverted mobile screen

**Comment by pftg** [comment]
Let's close for now
