### ISSUE TITLE
Review Search Console & Audit Errors

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#322]
по сайту надо разобрать https://search.google.com/u/0/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.jetthoughts.com%2F&item_key=CAMYJyAC - crawl anomaly

![image](https://user-images.githubusercontent.com/125715/40310232-c3cf9292-5d14-11e8-9112-f4b15faa2454.png)

![image](https://user-images.githubusercontent.com/125715/40310235-c7b0cc14-5d14-11e8-856b-0e1a4e227bf3.png)

**Comment by andriyParashchuk** [comment]
- Search Console - it is ok
![1527150854745](https://user-images.githubusercontent.com/23320186/40473982-732d8612-5f46-11e8-8e6a-0ff906ddf3c1.jpg)
- Canonical tag will be fix in #330

**Comment by andriyParashchuk** [comment]
@pftg @obliviusm @sweatC pls check and close
