### ISSUE TITLE
Migrate posts from old blog to jtway

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#323]
We need to migrate posts from old blog to jtway if there is usage on GA for last 6 month.

/blog/tricks/2011/04/04/add-current-date-to-text-document.html
/blog/tricks/2010/02/19/rails-assets-host-with-ssl.html
/blog/tech/2010/05/17/change-size-of-images-shell-script.html
/blog/tech/2009/12/26/show-log-file-from-remote-server.html
/blog/tech/2009/10/29/thin-authlogic-session-safari.html
/blog/team/2014/04/17/how-to-learn-ruby.html
/blog/tricks/2012/11/28/multiple-likes-for-one-page.html
/blog/tech/2010/09/26/installing-pg-gem-on-mac-os.html
/blog/tech/2010/07/11/geoipcity-on-mac-os.html
/blog/team/2015/02/02/how-we-hire-developers-at-jetthoughts.html
/tech/2013/09/26/capistrano-3-passing-parameters-to-your-task.html
/blog/tech/2010/03/01/remote-rails-console.html
/blog/tricks/2009/10/03/convert-authors-names-in-mercurial.html
/blog/tricks/2009/12/16/postgresql-insert-not-valid-unicode-values.html
/blog/tech/2011/09/24/change-factory-girl-directory-path-for-rails-3-generator.html
/blog/tech/2010/02/14/convert-bplist-to-xml.html
/blog/tech/2009/10/23/openssl-with-nginx-and-untrusted-ca.html

**Comment by pftg** [comment]
@sweatC please create list of posts which should be migrated

**Comment by sweatC** [comment]
@pftg  Here is a List(last 6 months):
- /blog/tricks/2011/04/04/add-current-date-to-text-document.html
- /blog/tricks/2010/02/19/rails-assets-host-with-ssl.html
- /blog/tech/2010/05/17/change-size-of-images-shell-script.html
- /blog/tech/2009/12/26/show-log-file-from-remote-server.html
- /blog/tech/2009/10/29/thin-authlogic-session-safari.html
- /blog/team/2014/04/17/how-to-learn-ruby.html
- /blog/tricks/2012/11/28/multiple-likes-for-one-page.html
- /blog/tech/2010/09/26/installing-pg-gem-on-mac-os.html
- /blog/tech/2010/07/11/geoipcity-on-mac-os.html
- /blog/team/2015/02/02/how-we-hire-developers-at-jetthoughts.html
- /tech/2013/09/26/capistrano-3-passing-parameters-to-your-task.html
- /blog/tech/2010/03/01/remote-rails-console.html
- /blog/tricks/2009/10/03/convert-authors-names-in-mercurial.html
- /blog/tricks/2009/12/16/postgresql-insert-not-valid-unicode-values.html
- /blog/tech/2011/09/24/change-factory-girl-directory-path-for-rails-3-generator.html
- /blog/tech/2010/02/14/convert-bplist-to-xml.html
- /blog/tech/2009/10/23/openssl-with-nginx-and-untrusted-ca.html

**Comment by pftg** [comment]
@sweatC

**Comment by andriyParashchuk** [comment]
@sweatC pls add more info how migrate posts from old blog

**Comment by sweatC** [comment]
@andriyParashchuk in this branch you will find all `posts`.
https://github.com/jetthoughts/jetthoughts.github.io/tree/archive-20180327/_posts/blog

**Comment by andriyParashchuk** [comment]
![1528462289421](https://user-images.githubusercontent.com/23320186/41159059-dd0b4828-6b33-11e8-85f3-217d8e291a9d.jpg)
Added draft post on JTway.com
@pftg @sweatC pls check

**Comment by pftg** [comment]
@andriyParashchuk we need also redirects to them to add

**Comment by pftg** [comment]
![image](https://user-images.githubusercontent.com/125715/41161908-f12257f8-6b3c-11e8-9ea0-7b4f25c5ea41.png)

please replace markups with medium formats

**Comment by pftg** [comment]
`{% highlight ruby linenos=table %} g.fixture_replacement :factory_girl, :dir => 'spec/factories' {% endhighlight %}` => 

```markdown
g.fixture_replacement :factory_girl, :dir => 'spec/factories'
```

**Comment by andriyParashchuk** [comment]
@pftg replaced markups with medium formats
Redirects will be a fix #338

**Comment by pftg** [comment]
@andriyParashchuk please ask someone to verify and publish

**Comment by andriyParashchuk** [comment]
@miry @obliviusm @sweatC pls check

- https://jtway.co/openssl-with-nginx-and-untrusted-ca-b4f37c19e29d
- https://jtway.co/convert-authors-names-in-mercurial-11fc3324c26f
- https://jtway.co/remote-rails-console-22dd4c2ff84d
- https://jtway.co/postgresql-insert-not-valid-unicode-values-a887edb464c6
- https://jtway.co/convert-bplist-to-xml-3784c7ba0b3
- https://jtway.co/add-current-date-to-text-document-3494085d072d
- https://jtway.co/rails-assets-host-with-ssl-a843ded59ce4
- https://jtway.co/change-size-of-images-shell-script-5067e40ebd82
- https://jtway.co/show-log-file-from-remote-server-3d5f2489d2c
- https://jtway.co/how-to-learn-ruby-bd15fb731fc5
- https://jtway.co/multiple-likes-for-one-page-2abdb9ee5e97
- https://jtway.co/installing-pg-gem-on-mac-os-1a9fb11a4a31
- https://jtway.co/change-factory-girl-directory-path-for-rails-3-generator-80b19916b492
- https://jtway.co/how-we-hire-developers-at-jetthoughts-d71e8b88e62c
- https://jtway.co/geoip-city-on-mac-os-bcc42bd7601

**Comment by pftg** [comment]
Posts shared on https://medium.com/jetthoughts/stories/submissions

**Comment by pftg** [comment]
for now, we need to publish this unlisted only:

![image](https://user-images.githubusercontent.com/125715/41709168-38ddb336-754b-11e8-8200-342005c5b5b8.png)

![image](https://user-images.githubusercontent.com/125715/41709151-2dddc25a-754b-11e8-833f-b7f7e5a88520.png)

**Comment by pftg** [comment]
@SviridovSV please check that posts (which has not been published yet) looks good to publish

**Comment by SviridovSV** [comment]
@pftg Checked:
1.  https://medium.com/@andriyparashchuk/b4f37c19e29d  '...and found a free provider http://www.instantssl.com/ COMODO' perhaps, would be better '...by COMODO'
2.  https://medium.com/@andriyparashchuk/80b19916b492  Does we allow ruby-code to be in one string?
If it is OK, then no questions have, else there are some places, where code in one string

**Comment by pftg** [comment]
@andriyParashchuk, please check and fix

**Comment by andriyParashchuk** [comment]
Fixed
Pls check

**Comment by pftg** [comment]
Published
