### ISSUE TITLE
Research Seo Report

### ISSUE THREAD

**Issue by andriyParashchuk** [jetthoughts/jt.github.io#324]
Research and improve
https://sitechecker.pro/seo-report/https://www.jetthoughts.com

**Comment by sweatC** [comment]
@pftg @andriyParashchuk pls check
Here is research:
![image](https://user-images.githubusercontent.com/15202961/40379357-88d7de7a-5dfe-11e8-83f6-6637dbae5b45.png)
![image](https://user-images.githubusercontent.com/15202961/40379470-d97ce8b6-5dfe-11e8-9032-657ab03e9080.png)
## Errors:
![image](https://user-images.githubusercontent.com/15202961/40379520-f6397398-5dfe-11e8-8435-6b5de2f256f4.png)
![image](https://user-images.githubusercontent.com/15202961/40379671-6ca2514e-5dff-11e8-82d1-6cd79eab9bec.png)
![image](https://user-images.githubusercontent.com/15202961/40379767-acb79d0c-5dff-11e8-8da0-c060bf389cce.png)
## Warnings:
![image](https://user-images.githubusercontent.com/15202961/40379801-cf004cba-5dff-11e8-8b3a-941c671b1a70.png)
![image](https://user-images.githubusercontent.com/15202961/40379817-e0f5ff8c-5dff-11e8-9c18-3085bac3b44d.png)
[Consolidate duplicate URLs](https://support.google.com/webmasters/answer/139066?hl=en)
[Explore What a Canonical URL Is and When You Need to Use It](https://sitechecker.pro/canonical-url/)
![image](https://user-images.githubusercontent.com/15202961/40379966-515b0498-5e00-11e8-9a26-09b05cf472d1.png)
[Reduce the size of the above-the-fold content](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent)
![image](https://user-images.githubusercontent.com/15202961/40379986-6912bd74-5e00-11e8-82a8-803ea1eb5029.png)
[Leverage Browser Caching](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching)

**Comment by pftg** [comment]
Need someone to create issues from this report and schedule into tasks for jt contribution

**Comment by obliviusm** [comment]
@sweatC pls add these all info to SEO epic
pls create issues for errors and canonical link warning. decide whether other warnings are important and should we create issues for them

**Comment by sweatC** [comment]
@obliviusm I've added info to the Epic.
Could we close this one?

**Comment by obliviusm** [comment]
@sweatC have you created issues?

**Comment by sweatC** [comment]
Issues added: https://github.com/jetthoughts/jetthoughts.github.io/issues/327, https://github.com/jetthoughts/jetthoughts.github.io/issues/328, https://github.com/jetthoughts/jetthoughts.github.io/issues/329, https://github.com/jetthoughts/jetthoughts.github.io/issues/330.

**Comment by obliviusm** [comment]
@sweatC Don't close your own issues on review. That's responsibility of a reviewer!
