### ISSUE TITLE
SEO 2: After Review and Report

### ISSUE THREAD

**Issue by obliviusm** [jetthoughts/jt.github.io#326]
We have some problems related to SEO and performance, which we could fix.

https://sitechecker.pro/seo-report/https://www.jetthoughts.com

![image](https://user-images.githubusercontent.com/15202961/40379357-88d7de7a-5dfe-11e8-83f6-6637dbae5b45.png)
![image](https://user-images.githubusercontent.com/15202961/40379470-d97ce8b6-5dfe-11e8-9032-657ab03e9080.png)
## Errors:
![image](https://user-images.githubusercontent.com/15202961/40379520-f6397398-5dfe-11e8-8435-6b5de2f256f4.png)
![image](https://user-images.githubusercontent.com/15202961/40379671-6ca2514e-5dff-11e8-82d1-6cd79eab9bec.png)
![image](https://user-images.githubusercontent.com/15202961/40379767-acb79d0c-5dff-11e8-8da0-c060bf389cce.png)
## Warnings:
![image](https://user-images.githubusercontent.com/15202961/40379801-cf004cba-5dff-11e8-8b3a-941c671b1a70.png)
![image](https://user-images.githubusercontent.com/15202961/40379817-e0f5ff8c-5dff-11e8-9c18-3085bac3b44d.png)
[Consolidate duplicate URLs](https://support.google.com/webmasters/answer/139066?hl=en)
[Explore What a Canonical URL Is and When You Need to Use It](https://sitechecker.pro/canonical-url/)
![image](https://user-images.githubusercontent.com/15202961/40379966-515b0498-5e00-11e8-9a26-09b05cf472d1.png)
[Reduce the size of the above-the-fold content](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent)
![image](https://user-images.githubusercontent.com/15202961/40379986-6912bd74-5e00-11e8-82a8-803ea1eb5029.png)
[Leverage Browser Caching](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching)

**Comment by andriyParashchuk** [comment]
![1527151181884](https://user-images.githubusercontent.com/23320186/40474685-5cce50d4-5f48-11e8-9461-f831f87b22cf.jpg)
![1527155790827](https://user-images.githubusercontent.com/23320186/40478529-f658cf6e-5f51-11e8-861e-b3860ce5086c.jpg)

**Comment by sweatC** [comment]
Made SEO and performance Audits - https://github.com/jetthoughts/jetthoughts.github.io/issues/388, created related tasks for SEO 2.
