### ISSUE TITLE
Fix accesible index page

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#329]
![image](https://user-images.githubusercontent.com/15202961/40379767-acb79d0c-5dff-11e8-8da0-c060bf389cce.png)

**Comment by pftg** [comment]
Any updates for this issue?

**Comment by SviridovSV** [comment]
@pftg First of all, I propose to check server settings, smth like "Options Indexes". Also I read on forum that it is a standard convention that webservers send /index.html (or some variant like /index.htm or /index.php or whatever extension applies) when no filename is provided, so / is only a kind of alias for it.
Perhaps, this is one of the way to attract clients for seo-services https://forum.joomla.org/viewtopic.php?t=961415

**Comment by miry** [comment]
@SviridovSV Can you check do we have access to webserver?

**Comment by SviridovSV** [comment]
@miry We have no access to webserver, perhaps, we can connect to their support. Also we can assume that github uses Apache web server and add .htaccess, where implement 301 redirect from /index.html to root

**Comment by pftg** [comment]
yep, if github page does not allow to setup so we need to clos ethis

**Comment by miry** [comment]
But according the Sergey.  They are correct pages. Identical. Github pages allows to create any pages.

**Comment by miry** [comment]
How can we reproduce error?

**Comment by pftg** [comment]
This issue is related to https://github.com/jetthoughts/jetthoughts.github.io/issues/326

@miry you could recheck on https://sitechecker.pro/seo-report/https://www.jetthoughts.com

**Comment by miry** [comment]
в robots.txt можно заблокировать index.html
