### ISSUE TITLE
Add mail to link with recipient, subject and body

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#33]
Recipient: JetThoughts info@jetthoughts.com
Subject: Interested in working with you

**Comment by mir4a** [comment]
@annkuptsova  pls check (click on mail link at the footer), also check how subject fit our needs?

**Comment by tehhi42** [comment]
@mir4a when i click on the mail link the mail wizard opens. There is neither recipient, nor subject in it. http://minus.com/lbusIFxczCy9Hy

**Comment by miry** [comment]
@tehhi42 it works for me.

**Comment by miry** [comment]
@tehhi42 pls post here what browser and os  did you use.

**Comment by miry** [comment]
@tehhi42 try other OS and browsers, to be sure that the problem only in Chrome + Linux

**Comment by miry** [comment]
@tehhi42 why do you test it? it was assigned to @annkuptsova

**Comment by tehhi42** [comment]
@miry Sorry, I thought that it was twelli task.

**Comment by tehhi42** [comment]
@miry I tested it, because @annkuptsova was busy with other tasks.

**Comment by annkuptsova** [comment]
Firefox and chrome for Linux mint gives, same result http://dl.dropbox.com/u/19920739/Workspace%201%28004%29.png

firefox for windows http://dl.dropbox.com/u/19920739/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202014-02-12%2013.57.36.png

**Comment by miry** [comment]
Linux does not understand mail to link. hm. It is not the issue. at least we have Windows and MacOS
