### ISSUE TITLE
Add canonical link tag

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#330]
![image](https://user-images.githubusercontent.com/15202961/40379817-e0f5ff8c-5dff-11e8-9c18-3085bac3b44d.png)
[Consolidate duplicate URLs](https://support.google.com/webmasters/answer/139066?hl=en)
[Explore What a Canonical URL Is and When You Need to Use It](https://sitechecker.pro/canonical-url/)

**Comment by andriyParashchuk** [comment]
Fixed in #325
