### ISSUE TITLE
Agent Inbox Use Case Page

### ISSUE THREAD

**Issue by obliviusm** [jetthoughts/jt.github.io#343]
Resources:
https://www.figma.com/file/wmRuaLaG0wwnOE9kBWfnMn/Jetthoughts-2?node-id=1%3A2
https://drive.google.com/drive/u/1/folders/10u983TDr5TbtvF27Vgcyt9JisbmqICYo

**Comment by pftg** [comment]
We have published our AI case for desktop! Left only Mobile! willl be fixed later
