### ISSUE TITLE
AI: Add ghost inspector tests

### ISSUE THREAD

**Issue by obliviusm** [jetthoughts/jt.github.io#345]
Add test for 1600x900 resolution

**Comment by obliviusm** [comment]
https://app.ghostinspector.com/tests/5bb4b1b8a4c3144249ec834c

**Comment by obliviusm** [comment]
Added test for 1600x900 resolution https://app.ghostinspector.com/tests/5bb5dbbe28f40f4c0ccd20d7

**Comment by obliviusm** [comment]
@andriyParashchuk pls review

**Comment by andriyParashchuk** [comment]
LGTM
