### ISSUE TITLE
CC licence

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#35]
Need to think how to put some credits to icon designers

https://thenounproject.zendesk.com/hc/en-us/articles/200744853-How-do-I-attribute-Multiple-Symbols-

https://thenounproject.zendesk.com/hc/en-us/articles/200509928-What-is-the-proper-way-to-attribute-CC-BY-icons-

https://thenounproject.zendesk.com/hc/en-us/articles/200509948-Medium-Specific-Attribution-Requirements-examples

**Comment by tehhi42** [comment]
Verified.
