### ISSUE TITLE
Audit Issues: Descriptive link text helps search engines understand your content.

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#356]
![image](https://user-images.githubusercontent.com/125715/46601981-8f04f600-caf7-11e8-8058-6aeb44476ba8.png)

**Comment by andriyParashchuk** [comment]
@pftg In design, this link has the text `LEARN MORE`. You think we need to change this text?

**Comment by pftg** [comment]
@andriyParashchuk could you research and propose a better name for it?

**Comment by andriyParashchuk** [comment]
@pftg It is a good name. Geting warning because name is duplicate, but it is the slideshow. So it is normal.

**Comment by pftg** [comment]
I mean could we add `More about Agent Inbox`?

**Comment by andriyParashchuk** [comment]
Yes, we can

**Comment by andriyParashchuk** [comment]
Fixed in #369
