### ISSUE TITLE
Broken Arrows for Services

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#358]
Browser: Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)
OS: Ubuntu
Width: 750 - 830
Height: 415

![image](https://user-images.githubusercontent.com/125715/46602501-0f782680-caf9-11e8-931f-d81800473c71.png)

**Comment by andriyParashchuk** [comment]
@pftg pls add resolution that are is with bug

**Comment by pftg** [comment]
@andriyParashchuk updated with width

**Comment by andriyParashchuk** [comment]
@pftg I think this is not a bug because this resolution is not standard
