### ISSUE TITLE
SEO: Add sitemap for AI

### ISSUE THREAD

**Issue by obliviusm** [jetthoughts/jt.github.io#360]

**Comment by andriyParashchuk** [comment]
![image](https://user-images.githubusercontent.com/23320186/55140897-d16fcd00-5141-11e9-91c7-154321f99d66.png)
![image](https://user-images.githubusercontent.com/23320186/55160625-6ab3d900-516c-11e9-9737-94c008bbc9d4.png)

**Comment by andriyParashchuk** [comment]
@pftg @ad-sys Already we have sitemap for AI page. Because we use `jekyll-sitemap` plugin for automated generate sitemap file. I think this ticket can close.
