### ISSUE TITLE
Categories and icons

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#38]
Need to think how many categories do we need and what icons to assign with them

**Comment by miry** [comment]
lets just add one by one. I think now we have only Tech. Found example of categories title http://www.wikihow.com/Special:Categorylisting.

**Comment by miry** [comment]
@mir4a find one icon for Tech category and update to all posts.

**Comment by mir4a** [comment]
@tehhi42 @annkuptsova @miry here is a few examples of icons:
![screen shot 2014-03-28 at 17 52 55](https://cloud.githubusercontent.com/assets/618900/2551765/0a7ce768-b692-11e3-9fa6-a57cfe5832b1.png)
![screen shot 2014-03-28 at 17 53 07](https://cloud.githubusercontent.com/assets/618900/2551766/0a95c9d6-b692-11e3-91f3-686135c70e23.png)
![screen shot 2014-03-28 at 17 53 19](https://cloud.githubusercontent.com/assets/618900/2551767/0aae7abc-b692-11e3-85be-24ba9910e2bf.png)
![screen shot 2014-03-28 at 17 54 27](https://cloud.githubusercontent.com/assets/618900/2551768/0ab04360-b692-11e3-8913-38e7d9f383e3.png)

**Comment by mir4a** [comment]
So, for now I have added these categories:
– books (or read, ebook)
– checklist (or todo list)
– database (or db)
– experimental (or hack, hackaton)
– magic (or hack)
– mobile (or app, responsive, appstore)
– team
– tech (or hardware, cpu)
– tricks (or hacks, tips)

**Comment by tehhi42** [comment]
Verified.
