### ISSUE TITLE
[UI] Change font size

### ISSUE THREAD

**Issue by andriyParashchuk** [jetthoughts/jt.github.io#385]
https://www.useloom.com/share/332575e3181742cdbd6b3a6003737791
Some improvments will be great to have:
![image](https://user-images.githubusercontent.com/23320186/54422870-13e3e380-4718-11e9-96db-2a6d644d32a5.png)

**Comment by ad-sys** [comment]
@andriyParashchuk Hi) what is the status on it?

**Comment by andriyParashchuk** [comment]
@ad-sys Fixed in #384
