### ISSUE TITLE
Run Audits and schedule improvements for Home & AI Case Pages

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#388]
- [x] Performance audits
- [x] SEO audits

**Comment by sweatC** [comment]
### After running SEO and Performance audits using LightHouse 4.0, I have got:
![image](https://user-images.githubusercontent.com/15202961/56950395-0e165600-6b3e-11e9-964e-ba70e9257c02.png)
Tested Structured Data - https://search.google.com/structured-data/testing-tool/#url=https%3A%2F%2Fwww.jetthoughts.com%2F:
![image](https://user-images.githubusercontent.com/15202961/56950544-6d746600-6b3e-11e9-93c6-e08f3b181381.png)
Tested Mobile Friendly - https://search.google.com/test/mobile-friendly?id=eDWfKeAVTLmUCMylZc54Eg:
![image](https://user-images.githubusercontent.com/15202961/56950641-a14f8b80-6b3e-11e9-85d4-bd222a3131bd.png)
### Performance issues:
1) I have said about it that converting to other format would deform our pictures:
![image](https://user-images.githubusercontent.com/15202961/56958576-4d02d680-6b53-11e9-806a-f4bed482ed9d.png)
2) Need to fix- https://developers.google.com/web/tools/lighthouse/audits/oversized-images:
![image](https://user-images.githubusercontent.com/15202961/56958634-77549400-6b53-11e9-9203-2ae1e376d05e.png)
3) Ensure text remains visible during webfont load - https://developers.google.com/web/updates/2016/02/font-display:
![image](https://user-images.githubusercontent.com/15202961/56958691-acf97d00-6b53-11e9-9152-bf4b063c110f.png)
4) Serve static assets with an efficient cache policy - https://developers.google.com/web/tools/lighthouse/audits/cache-policy:
![image](https://user-images.githubusercontent.com/15202961/56958728-cd293c00-6b53-11e9-9655-f22f479b5d83.png)
5) Minimize main-thread work - Consider reducing the time spent parsing, compiling and executing JS. You may find delivering smaller JS payloads helps with this:
![image](https://user-images.githubusercontent.com/15202961/56958774-f3e77280-6b53-11e9-87fa-62030fd2c0de.png)
6) Minimize Critical Requests Depth - https://developers.google.com/web/tools/lighthouse/audits/critical-request-chains:
![image](https://user-images.githubusercontent.com/15202961/56958811-16798b80-6b54-11e9-94e9-7bf467d7cd90.png)

**Comment by sweatC** [comment]
@pftg and @andriyParashchuk pls leave your thoughts about it and tell what needed to be done in next sprint and what we can drop out.

**Comment by pftg** [comment]
From this list, we could not fix only cache, all other stuff possible to fix. @sweatC please review backlog and add new items from this list without adding duplications

For sizes per images, we should have different files per different screens so we could show them only when needed.

**Comment by pftg** [comment]
@sweatC I have not found SEO audit, are you going to add it in another issue?

**Comment by pftg** [comment]
also, we have 2 pages: agent inbox and homepage; we need to verify for both

**Comment by sweatC** [comment]
@pftg using lighthouse audit I have got 100points - it's maximum in this tool. So there is nothing to fix in SEO. Also, I have checked for both pages.

**Comment by andriyParashchuk** [comment]
![image](https://user-images.githubusercontent.com/23320186/57069690-02fa2c00-6cde-11e9-8522-3b9ed56fae7c.png)

![image](https://user-images.githubusercontent.com/23320186/57069700-08f00d00-6cde-11e9-92ab-c7cc92af2373.png)

**Comment by pftg** [comment]
For SEO please use: https://sitechecker.pro/ and https://neilpatel.com/seo-analyzer/

**Comment by pftg** [comment]
![](https://cl.ly/a525c6/Image%202019-05-02%20at%2009.53.06.png)

**Comment by sweatC** [comment]
I have created tasks for SEO and Performance, also added SEO tools to Wiki: https://github.com/jetthoughts/jetthoughts.github.io/wiki/SEO-tools
