### ISSUE TITLE
Add author section for blog post

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#39]
- [x] Add markup and styling for author section. Reference http://blog-next-master.herokuapp.com/2014/01/04/lock-code-confirmation-in-learn-rubymotion-16.html 
  ![screen shot 2014-02-04 at 17 54 53](https://f.cloud.github.com/assets/618900/2077666/c142ab38-8db4-11e3-9091-e9a52306bae4.png)
- [x] Use data.yml for authors

**Comment by mir4a** [comment]
@miry check http://jetthoughts.github.io/tech/2013/09/26/capistrano-3-passing-parameters-to-your-task.html

**Comment by miry** [comment]
@mir4a pls replace: `twi` with twitter icon from glyph icons or fontawsome. Same for github.

**Comment by mir4a** [comment]
@annkuptsova pls verify

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified. 
http://minus.com/lB3JXjISKJBhp
http://minus.com/lb0XJ49BgzfDx7
http://minus.com/ld56UErMgsvCg
