### ISSUE TITLE
Fix LI preview to be show our details instead of WebDeveloment

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#397]
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.jetthoughts.com

![](https://cl.ly/ac5eef1135b9/Image%2525202019-04-18%252520at%25252023.47.16.png)

Examples from mailgun: https://www.loom.com/share/c434d28020ef48d1bb794abefd6f5d12

**Comment by andriyParashchuk** [comment]
![image](https://user-images.githubusercontent.com/23320186/56567415-8a002380-65bd-11e9-9a28-b026f2a54444.png)

**Comment by sweatC** [comment]
@pftg pls verify if it's good enough:
![image](https://user-images.githubusercontent.com/15202961/56887526-861b4800-6a7a-11e9-85f0-a81220e1ee7b.png)

**Comment by pftg** [comment]
Great
