### ISSUE TITLE
Fix Google Search Result presentation to be more like thoughtbot

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#399]
![](https://cl.ly/d5de53/Image%202019-04-23%20at%2014.02.15.png)

Related issue: #390

**Comment by sweatC** [comment]
1. The title has been changed:
![image](https://user-images.githubusercontent.com/15202961/56651620-2562c880-6692-11e9-8d6c-824ba889e9c5.png)
2. It is called sitelinks and the algorithm of showing sitelinks is automated, google only show sitelinks for results when it thinks they'll be useful to the user(https://support.google.com/webmasters/answer/47334?hl=en). Also, what do you want to see in this section?
3. Google suggests at first validate our structured data:
![image](https://user-images.githubusercontent.com/15202961/56651931-c94c7400-6692-11e9-9eed-ec2cca03596d.png)
Then I checked that for showing **search card** we have all needed meta information(https://github.com/jetthoughts/jetthoughts.github.io/blob/396-remove-title-from-preview/_includes/head.html#L61-L66).
Also, we have contacts(https://github.com/jetthoughts/jetthoughts.github.io/blob/396-remove-title-from-preview/_includes/head.html#L73-L79) that must be shown like:
![image](https://user-images.githubusercontent.com/15202961/56652125-45df5280-6693-11e9-9724-c6aeca694fab.png)

**Comment by pftg** [comment]
@sweatC what we need to do make google refresh data and show info about us?

**Comment by sweatC** [comment]
I think it will be fixed after https://github.com/jetthoughts/jetthoughts.github.io/issues/404

**Comment by pftg** [comment]
I'm not sure that they are related

**Comment by sweatC** [comment]
@pftg they are related, because of the broken schema, Google can't enable rich search results.

**Comment by pftg** [comment]
ok,let's fix first google search index problem

**Comment by sweatC** [comment]
After researching this problem I have found that:
1. We can't influence on some of the rich search results as showing up Site links or Rich card:
![image](https://user-images.githubusercontent.com/15202961/56852466-8275ad00-6924-11e9-96a3-88faaf0a374a.png)
2. We have coded needed logo and company name so, theoretically rich card must be shown, but Google says that the algorithm would decide if this important to show or not.

https://support.google.com/webmasters/answer/7358659?hl=en

**Comment by pftg** [comment]
@sweatC should we add https://schema.org/BreadcrumbList which are supported by Google?

**Comment by sweatC** [comment]
A breadcrumb trail on a page indicates the page's position in the site hierarchy. 
@pftg I think it is relevant only for big sites:
![image](https://user-images.githubusercontent.com/15202961/56949609-0950a280-6b3c-11e9-9a28-da0f190e59a8.png)
