### ISSUE TITLE
Post comment with staging url in github

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#403]
Need to get from lyoutube and integrate it here.

**Comment by pftg** [comment]
@sweatC please add labels for and describe problem not the solution in the issue description. What do you want to see at the end instead of how to do it.

**Comment by sweatC** [comment]
After each iteration of CircleCI, I want to see refreshed comment with a link to the staging.

**Comment by sweatC** [comment]
Closed because of https://github.com/jetthoughts/jetthoughts.github.io/pull/405
