### ISSUE TITLE
Fix Google Search errors

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#406]
After validation results, we need to take the next steps of fixing it:
![image](https://user-images.githubusercontent.com/15202961/56747266-4e648580-6786-11e9-88ff-f75bd9f1a836.png)

**Comment by pftg** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/125715/56776240-df158280-67d3-11e9-9ba9-1843d6bfde69.png)
