### ISSUE TITLE
Fix oversized images

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#412]
Properly Size Images - https://developers.google.com/web/tools/lighthouse/audits/oversized-images
I think if we got worse quality then we need to think about media query and remove big images for small screens.
![image](https://user-images.githubusercontent.com/15202961/57152840-4f786100-6ddd-11e9-9a14-fa5be599bcdc.png)

**Comment by andriyParashchuk** [comment]
Done in #447
