### ISSUE TITLE
Minimize Critical Requests Depth

### ISSUE THREAD

**Issue by sweatC** [jetthoughts/jt.github.io#416]
Consider reducing the length of chains, reducing the download time of resources  - https://developers.google.com/web/tools/lighthouse/audits/critical-request-chains:
![image](https://user-images.githubusercontent.com/15202961/57153489-1e009500-6ddf-11e9-96b0-49d8fca4caf1.png)

**Comment by andriyParashchuk** [comment]
This because we use custom fonts
