### ISSUE TITLE
Team page changes

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#42]
- [x] Use data.yml for team members data
- [ ] Remove surname for all teams except Asya and Anna
- [ ] Insert real data

**Comment by tehhi42** [comment]
![alyona](https://cloud.githubusercontent.com/assets/5908100/2616084/08e39350-bc02-11e3-8700-1e7cf1d8f9e2.jpg)
![elena](https://cloud.githubusercontent.com/assets/5908100/2616086/0b1fb306-bc02-11e3-81cc-e12e27f608cd.jpg)
![max](https://cloud.githubusercontent.com/assets/5908100/2616088/0dc79de4-bc02-11e3-8e62-3d15eb0baf1f.jpg)

**Comment by tehhi42** [comment]
@mir4a please add 
![ohkl8sb44p4](https://cloud.githubusercontent.com/assets/5908100/2740263/5d2a685a-c6cd-11e3-84ce-a2f2a669d9bc.jpg)

![6918710](https://cloud.githubusercontent.com/assets/5908100/2740270/9cea9c3a-c6cd-11e3-9cfa-c665944e1c72.jpg)

**Comment by tehhi42** [comment]
Verified.
