### ISSUE TITLE
Add screenshot tests for OpenApply case 

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#424]
https://app.ghostinspector.com/suites/5adaeeae6cca1a3596963eaa

**Comment by sweatC** [comment]
@pftg It seems that we need to purchase to activate ghost inspector and run tests:
![image](https://user-images.githubusercontent.com/15202961/67303173-bb20c880-f4fa-11e9-9b29-0ac61cae4353.png)
![image](https://user-images.githubusercontent.com/15202961/67303250-da1f5a80-f4fa-11e9-96ee-4939b87b7b8e.png)
![image](https://user-images.githubusercontent.com/15202961/67303324-fa4f1980-f4fa-11e9-8051-b5a0410ae28c.png)

**Comment by sweatC** [comment]
Fixed all AI Page tests and added tests for OA Page.
For the future to make changes easier and from one place it is good to have variables instead of 
just hardcoded text: https://ghostinspector.com/docs/variables/

**Comment by sweatC** [comment]
@pftg pls check

**Comment by pftg** [comment]
Perfect! Thanks a lot!
