### ISSUE TITLE
Home page footer

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#47]
http://minus.com/lPjd6XscqdW3c

**Comment by miry** [comment]
@tehhi42 let skip it for now. because it would be post section in v0.2.

**Comment by tehhi42** [comment]
@miry Let's skip it at all, because we are going to deploy all pages to production.

**Comment by tehhi42** [comment]
@mir4a Let's add site categories as we have discussed.

**Comment by tehhi42** [comment]
Verified.
