### ISSUE TITLE
Difference in layout

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#49]
Here is how home page looks on a small screen, Chrome. http://minus.com/lnLHPacAunO7v
And on a wide screen, Chrome http://minus.com/lIY6IaA9fsOjQ 
Small screen, Firefox http://minus.com/lLMWiRPQUnWef
Wide screen, Firefox http://minus.com/lbrILiVU5IXAY1

**Comment by tehhi42** [comment]
@miry Do we need to fix that?

**Comment by miry** [comment]
@tehhi42 I am not sure what is wrong. can you clarify it on images.

**Comment by tehhi42** [comment]
This issue is irrelevant.
