### ISSUE TITLE
Slogan on the main page

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#55]
Please have a look at some variants. I am interested in the opinions on the color, size and content itself. 
![selection_234](https://f.cloud.github.com/assets/5908100/2420875/827464fe-ab79-11e3-89a7-8db0fba2a655.png)
![selection_235](https://f.cloud.github.com/assets/5908100/2420876/862e597e-ab79-11e3-9bc0-f2a1b14280f6.png)
![selection_236](https://f.cloud.github.com/assets/5908100/2420879/88cfb72c-ab79-11e3-8051-596b2d3d70c8.png)
![selection_237](https://f.cloud.github.com/assets/5908100/2420880/8b100fdc-ab79-11e3-9478-96b55a6db1a9.png)
![selection_238](https://f.cloud.github.com/assets/5908100/2420882/8e92fca0-ab79-11e3-9d4b-0f2cf81e2f81.png)
![selection_239](https://f.cloud.github.com/assets/5908100/2420885/90c85bbe-ab79-11e3-8f0a-063730254549.png)

**Comment by mir4a** [comment]
1-й и 3-й лайк

**Comment by miry** [comment]
Rails Warriors :)

**Comment by miry** [comment]
Long phrases are not good as for me. Hard to remember.

**Comment by tehhi42** [comment]
а если так? ![selection_257](https://f.cloud.github.com/assets/5908100/2460219/ac280f16-af67-11e3-8413-7f931259c126.png)

**Comment by miry** [comment]
@tehhi42 ask guys

**Comment by tehhi42** [comment]
@mir4a Let's stick to the last variant.

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified.
