### ISSUE TITLE
Main page fixes

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#56]
http://minus.com/lEtmA1KX6XusY
http://minus.com/lsDtDP55vgaeO

**Comment by mir4a** [comment]
Выравнивание актуально?

**Comment by tehhi42** [comment]
Да.

**Comment by tehhi42** [comment]
What about social icons? Seems like they are not fixed.

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified.
