### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#60]

**Comment by mir4a** [comment]
@tehhi42 pls verify (I share you google spreadsheet where data are collected from our contact form http://www.jetthoughts.com/contact)

**Comment by tehhi42** [comment]
@mir4a http://minus.com/lAiKwXqeFDRnX

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
@mir4a http://minus.com/ljLMN2N3Vuf3a
http://minus.com/lHUX0bjPde1As
change Donetsk map to Nevada :-) http://minus.com/ljHkUAuZWmVBT

**Comment by mir4a** [comment]
@tehhi42 pls verify

**Comment by tehhi42** [comment]
Verified.
