### ISSUE TITLE
Make psd with 2nd version of fonts

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#61]

**Comment by mir4a** [comment]
![index_lato](https://cloud.githubusercontent.com/assets/618900/2600475/60b9bcde-baff-11e3-9cd8-6b10006e20f5.png)

**Comment by mir4a** [comment]
@tehhi42 pls check this version. It was my mistake, the previous version was saved in CMYK (for printing) color profile. The new one is in RGB (for monitors). This can cause only colours.
![index_lato_srgb](https://cloud.githubusercontent.com/assets/618900/2601459/6525c900-bb10-11e3-8b03-e43765735f42.png)

**Comment by mir4a** [comment]
@tehhi42 never mind
