### ISSUE TITLE
Design verification

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#67]
@annafoksha @pftg @miry @mir4a Please, verify that pngs added on Trello on November 29th represent the latest version of design (besides fonts)
![blog](https://cloud.githubusercontent.com/assets/5908100/2630751/5148bc2a-be4f-11e3-83c8-a8c86bd2cd36.png)
![404](https://cloud.githubusercontent.com/assets/5908100/2630752/5148d6ce-be4f-11e3-9faf-52b986a898ed.png)
![blog-single](https://cloud.githubusercontent.com/assets/5908100/2630753/51492048-be4f-11e3-97d0-7dba0c14c47f.png)
![careers](https://cloud.githubusercontent.com/assets/5908100/2630754/5149a1bc-be4f-11e3-8834-18450cac936e.png)
![contacts](https://cloud.githubusercontent.com/assets/5908100/2630755/514c1b2c-be4f-11e3-9d41-f80efb584bc0.png)
![how-we-work](https://cloud.githubusercontent.com/assets/5908100/2630756/514c1910-be4f-11e3-938c-0f87621b844a.png)
![index](https://cloud.githubusercontent.com/assets/5908100/2630757/5162d5b0-be4f-11e3-8558-4d358ec03300.png)
![our-team](https://cloud.githubusercontent.com/assets/5908100/2630758/5162e64a-be4f-11e3-8e2e-73996f16f272.png)
![portfolio-single](https://cloud.githubusercontent.com/assets/5908100/2630759/51634bf8-be4f-11e3-8e60-2dbfa5395e20.png)
![portfolio](https://cloud.githubusercontent.com/assets/5908100/2630760/51636cfa-be4f-11e3-87d9-618b770ff4b0.png)

**Comment by annafoksha** [comment]
да, похоже на последнию версию. кроме шрифтов) здесь они такие как на последнем psd
