### ISSUE TITLE
[Team] - member's blocks heights

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#84]
http://note.io/1hfojPA

**Comment by mir4a** [comment]
@pftg она будет одной высоты если: 
1. Высота блока будет жестко зафискирована и внутри блока может появится вертикальный скрол, така как количество слов у каждого разное.
2. Количество слов у всех будет одинаковое.

**Comment by pftg** [comment]
:+1: ну так наверное надо кол-во слов наверное уменьшить ;)

**Comment by mir4a** [comment]
@pftg ну это не наши методы – подгонять контент под картинку. Ровным счетом должно быть наоборот – контент главный. Ещё вариант считать под каждую ширину экрана самый высокий блок и jQuery менять высоту для всех.

**Comment by mir4a** [comment]
@pftg pls verify

**Comment by pftg** [comment]
:+1:
