### ISSUE TITLE
Mobile homepage bg

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#88]
![14 - 1](https://cloud.githubusercontent.com/assets/618900/2767509/e05d62ae-ca38-11e3-929f-f06396d61306.png)

**Comment by mir4a** [comment]
@pftg pls verify

**Comment by pftg** [comment]
perfecto!

**Comment by pftg** [comment]
even better then on desktop

**Comment by pftg** [comment]
- by the way, should we add JT logo for mobile version?
- also, may we reduce size of top bar?
