### ISSUE TITLE
Insert real content

### ISSUE THREAD

**Issue by mir4a** [jetthoughts/jt.github.io#9]
- [x] insert conetnt https://docs.google.com/a/jetthoughts.com/document/d/12mpIT1fViFP8SGol2Ypayx5yWo3wwYEdXn5HXJszVLo/edit
- [x] insert contact info

**Comment by mir4a** [comment]
@tehhi42 pls verify home page, for other pages create new issues

**Comment by tehhi42** [comment]
@mir4a please have a look at my suggestions
http://minus.com/l6fMzwafmjQdY
http://minus.com/lgzXhjTPmZeRf
http://minus.com/lsV7Tz82tMNts
http://minus.com/lhAhqTgPoBWDa

**Comment by miry** [comment]
@tehhi42 also can you check the Title: 'JetThoughts Home'. Can you find a good one. Or use the old.

**Comment by tehhi42** [comment]
resolved in #29.
