### ISSUE TITLE
Allow user edit posts from Github

### ISSUE THREAD

**Issue by miry** [jetthoughts/jt.github.io#90]
We should not use any external tools to build pages except GithubPages. It was the main goal to use jekyll. If we could not do this, will think to use another tool. But for now we should not use custom plugins.

**Comment by mir4a** [comment]
В чем проблема это делать в ветке development, а потом после вычитки дернуть кого-нить из ребят запустить `rake publish`?

Сейчас же, с таким воркфловом, мы можем юзать assets pipeline, у нас есть кастомные страницы категорий, тэгов.

**Comment by miry** [comment]
проблема нужно сделать git clone, git checkout, rake publish.

Изначально выбиралась github pages что бы этого не делать.

**Comment by mir4a** [comment]
Проблема будет, если вручную создать страницы категорий и (не дай боже) тегов, но зато можно будет править в гитхабе без лишних телодвижений. Так вот, потом будет проблема за страницами категорий и тегов уследить.

Или отказываемся от них вообще, максимально просто. Но тогда проблема с портфолио, вакансиями – это всё взаимосвязано. Сейчас это всё генерится автоматом, без кастомного плагина будет беда – эти страницы не будут исключаться из общего потока пагинации и блога. То есть, в блоге будут выводиться не только посты, но и записи из портфолио и вакансии.

**Comment by miry** [comment]
Мы можем сделать статику для портфолио?
Полность страниц где используем эти плагины?

Посты только для блога. все остальное статика.

**Comment by miry** [comment]
Еще один момент, давайте на будующее обуждать такого рода махинаций и решать их до а не после.

**Comment by miry** [comment]
thanks for you help @mir4a 
I am appreciate it.

**Comment by mir4a** [comment]
я махинатор :bangbang:

**Comment by mir4a** [comment]
@miry дай мне доступ на запись и я всё исправлю! :surfer:
