### ISSUE TITLE
Investigate what to put in footer

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#97]

**Comment by tehhi42** [comment]
I think that the best variant - to provide links to the main pages http://screencast.com/t/kCeeB8GZEe instead of http://screencast.com/t/CsZ9ox2V3. @miry @mir4a @pftg your thoughts?

**Comment by pftg** [comment]
:+1:

**Comment by tehhi42** [comment]
@mir4a let's put the links to the site pages in the footer.

**Comment by mir4a** [comment]
@tehhi42 I think we should close this issue, because it's duplicated in #111

**Comment by tehhi42** [comment]
@mir4a Agree.
