### ISSUE TITLE
Colors are incorrect from original design

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#99]
http://note.io/1n2MIxz

**Comment by tehhi42** [comment]
@pftg is it going to be fixed?

**Comment by pftg** [comment]
@tehhi42 what do you think, has this been fixed?

**Comment by tehhi42** [comment]
@pftg Talked to Miroslav. This issue has already been fixed. Here you can see that now colors look like in the original design http://screencast.com/t/Zo2XycpIdN
